env:
  es6: true
  node: true
extends:
  - airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  ecmaFeatures:
    optionalChaning: true
rules:
  comma-dangle: ["error", "never"]
  import/no-dynamic-require: off
  global-require: off
  consistent-return: off
  no-underscore-dangle: ["error", { "allow": ["_id", "_plain_password"] }]
  guard-for-in: off
  no-restricted-syntax: off
  no-throw-literal: off
